### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by PaoloBenigni** [rickyhan/tectonicdb#6]
I received this error on running cargo install tectonicdb
```

error[E0554]: #![feature] may not be used on the stable release channel
 --> .\.cargo\registry\src\github.com-1ecc6299db9ec823\tectonicdb-0.2.0\src/lib/lib.rs:1:1
  |
1 | #![feature(conservative_impl_trait)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: failed to compile `tectonicdb v0.2.0`, intermediate artifacts can be found at \AppData\Local\Temp\cargo-install.aFn6bCR7Zc4B`

Caused by:
  Could not compile `tectonicdb`.
```

**Comment by rickyhan** [comment]
Please compile with latest nightly(1.24.0) toolchain.

**Comment by PaoloBenigni** [comment]
Yup, just caught that.
